# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
    commit-message:
      prefix: ci
      prefix-development: ci
      include: scope
    labels:
      - pinned
      - dependencies
      - gha

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
    commit-message:
      prefix: fix
      prefix-development: build
      include: scope
    labels:
      - pinned
      - dependencies
      - mvn
